name: Update Repository

    on:
      schedule:
        - cron: "* * * * *"
      workflow_dispatch:

    jobs:
      update-repo:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout Repository
            uses: actions/checkout@v2

          - name: Update Repository
            run: |
              git pull origin main